CAVASOL/Air-bandb

- app/assets/stylesheets/pages.scss
- app/controllers/pages_controller.rb
- app/helpers/pages_helper.rb
- app/views/pages/home.html.erb
- config/routes.rb
- test/controllers/pages_controller_test.rb
> routes are done

- app/assets/stylesheets/components/_card_product.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/pages/dashboard.html.erb
> dashboard show bookings

- app/assets/stylesheets/_flats.scss
- app/assets/stylesheets/application.scss
- app/views/flats/index.html.erb
- app/views/layouts/application.html.erb
Flats index with View and flats scss finished
> Flats index views

- app/controllers/bookings_controller.rb
- app/views/pages/dashboard.html.erb
> booking update fixed

- app/controllers/flats_controller.rb
- app/views/flats/_form.html.erb
- app/views/flats/edit.html.erb
- app/views/flats/new.html.erb
- db/seeds.rb
Edit and create view
Create form 
Render form to create and edit in each view
> create and edit flat listing

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- db/seeds.rb
Finished the pages-home (controller,view,scss)
> Pages home

- app/controllers/flats_controller.rb
- app/views/flats/_form.html.erb
Added the photos upload to the listing form to create and update.
> Upload photos to form

- app/views/shared/_navbar.html.erb
Added dashboard link on home page's nav
> home nav dashboard added

- db/seeds.rb
> Seed location changed

- app/controllers/flats_controller.rb
- app/controllers/pages_controller.rb
- app/views/flats/index.html.erb
Fixed search functions -now user ables to search by name,description,location (fixing pages controller & flats controller)
> finished search function controller

- app/inputs/currency_input.rb
> fix currency

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/flats/_index.scss
- app/controllers/flats_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/flat.rb
- app/views/flats/_info_window.html.erb
- app/views/flats/index.html.erb
- app/views/layouts/application.html.erb
- config/initializers/geocoder.rb
- config/webpack/environment.js
- db/migrate/20211201035408_add_coordinates_to_flats.rb
- db/schema.rb
- package.json
- yarn.lock
- installed geocode gem and yarn add mapbox-gl
- added map with marker & info box
> geocode with map added

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Update style of sign in form
Update style of log in form
Update style of forgot my password
> styling sign up forms

- app/views/flats/show.html.erb
> New review

- app/models/booking.rb
- app/views/flats/show.html.erb
created a condition on booking page where the owner cannot make bookings
> Flats show bookings controller

- app/controllers/flats_controller.rb
- app/views/shared/_navbar.html.erb
- package.json
- yarn.lock
Advanced search which includes Capacity and Price per night Search
> Search edit

- app/controllers/flats_controller.rb
- app/models/flat.rb
- app/views/flats/index.html.erb
- app/views/pages/dashboard.html.erb
Reorganized Edit and Delete options in user dashboard. 
Delete path fixed with the dependance on bookings.
> delete path fixed

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/flats/_index.scss
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
Styled the sign in, log in and password forms
Added the possibility to attach profile pic when sign in.
Avatar pic appears in navbar
> Avatar sign in

- app/assets/stylesheets/flats/_index.scss
> style review

- app/assets/stylesheets/flats/_bookings.scss
- app/views/flats/show.html.erb
minor changes on show page and split the css for booking from homepage
> show-bookingcss

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> Landing page scss

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
fixing margin on the the landing page
> fixing margin on the landingpage

- app/views/pages/home.html.erb
refactoring code on pages home
> code refactoring on pages home

- app/controllers/bookings_controller.rb
- app/views/devise/sessions/new.html.erb
If user tries to book without being logged in he is redirected tot he log in page (where he can also sign in if not).
> Login alert

- app/views/bookings/show.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/flats/_form.html.erb
- app/views/flats/_info_window.html.erb
- app/views/flats/edit.html.erb
- app/views/flats/new.html.erb
- app/views/flats/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
> fixed footer

- app/controllers/flats_controller.rb
fixed flats controller for adding new pictures
> fixed flats controller for photos added

- app/views/flats/show.html.erb
> Edit flats
